# https://docs.docker.com/compose/compose-file/
name: suedwebs

services:
  server:
    build: .
    env_file: .env
    ports:
      - ${API_PORT}:3000
    restart: ${RESTART_POLICY}
    mem_limit: ${HARD_MEMORY_LIMIT}
    mem_reservation: ${SOFT_MEMORY_LIMIT}
